/* Start-up: wires the tab bar, cards and farm table, sets the initial view and draws. Loaded last by index.html.
   ES module (spec 3 step 2): imports name what this file needs from other modules, the export list at the end what it offers. */
// every page module in the original load order (modules that export nothing still run their start-up code)
import "./core/data.js";
import "./core/util.js";
import "./core/wake.js";
import "./core/feed.js";
import "./features/map/canvas.js";
import "./features/map/tiles.js";
import "./features/map/layers/gas.js";
import "./features/map/layers/grid.js";
import "./features/map/layers/dc.js";
import "./features/map/layers/interconnection.js";
import "./features/map/view.js";
import "./core/flags.js";
import "./features/map/layers/bathy.js";
import "./features/map/layers/zones.js";
import "./features/map/paint.js";
import "./features/map/sidebar.js";
import "./features/compare/compare.js";
import "./core/chart.js";
import "./core/router.js";
import "./core/cmp.js";
import "./features/market/heatmap.js";
import "./features/market/market.js";
import "./features/market/capture.js";
import "./features/system/system.js";
import "./features/system/gie.js";
import "./features/map/events.js";
import "./features/flags/table.js";
import "./features/flags/drilldown.js";
import "./core/sources.js";
import "./features/data/data.js";
import "./features/newsletter/newsletter.js";
import { F, FEED, S, inC } from "./core/data.js";
import { $, fg, fmt } from "./core/util.js";
import { K_DEF } from "./core/wake.js";
import { N0, SRC, dl } from "./core/feed.js";
import { HOME, V, clampV, fit, size } from "./features/map/canvas.js";
import { draw } from "./features/map/view.js";
import { MO, moSet } from "./features/map/layers/zones.js";
import { go } from "./features/map/sidebar.js";
import { agg, dash } from "./features/compare/compare.js";
import { aggW, dtip, hourAt, ms } from "./core/chart.js";
import { tab } from "./core/router.js";
document.body.dataset.tab=S.tab||"map";$("footd").ontoggle=()=>{if($("footd").open)$("foot2").innerHTML=$("foot").innerHTML};

$("tabs").onclick=e=>{const b=e.target.closest("button[data-t]");if(b)tab(b.dataset.t)};
$("cards").onclick=e=>{const c=e.target.closest(".card");if(c)go(c.dataset.c===S.c?null:c.dataset.c,null)};
$("ftab").onclick=e=>{const th=e.target.closest("th");if(th){if(th.dataset.k==="sp"||th.dataset.k==="sw")return;S.sort=[th.dataset.k,S.sort[0]===th.dataset.k?-S.sort[1]:(["n","c"].includes(th.dataset.k)?1:-1)];draw();return}
 const tr=e.target.closest("tbody tr");if(tr){const i=+tr.dataset.i;tab("map");go(F[i].c,i)}};
$("cards").onmousemove=e=>{const sv=e.target.closest("svg");if(!sv){if(S.hh>=0){S.hh=-1;dash()}$("dtip").style.display="none";return}const h=hourAt(sv,e,3);
 if(h!==S.hh){S.hh=h;dash()}const fc=F.filter(f=>inC(f,sv.dataset.c)),a=agg(fc);dtip(e,sv.dataset.c+" · "+dl(h)+(h>N0?" (forecast)":"")+" · "+fg(a.P[h])+(a.P[h]==null?"":" · CF "+(100*a.P[h]/a.inst).toFixed(0)+"%")+" · wind "+ms(aggW(fc)[h]))};
$("cards").onmouseleave=()=>{S.hh=-1;$("dtip").style.display="none";dash()};
$("ftab").onmousemove=e=>{const sv=e.target.closest("svg");if(!sv){$("dtip").style.display="none";return}const f=F[+sv.dataset.i],h=hourAt(sv,e,2);
 dtip(e,f.n+" · "+dl(h)+(h>N0?" (forecast)":"")+" · "+fmt(f.P[h])+(f.P[h]==null?"":" · CF "+(100*f.P[h]/f.inst).toFixed(0)+"%")+(f.U48[h]!=null?" · "+f.U48[h].toFixed(1)+" m/s from "+f.D48[h]+"°":""))};
$("ftab").onmouseleave=()=>{$("dtip").style.display="none"};
$("LV").checked=!!FEED;
$("foot").innerHTML="Map: in-browser Jensen/Gaussian on "+(FEED?"the forecast wind (or what-if sliders)":"what-if wind")+". Compare: "+(FEED?"PyWake results from feed.json.":"in-browser models on synthetic wind.")+(FEED&&SRC==="openmeteo"?" <a href='https://open-meteo.com/' style='color:inherit'>Weather data by Open-Meteo.com</a> (CC BY 4.0).":"")+" Power and thrust curves per turbine type from the EuroWindWakes database (PyWake generic curves). <i>Italic</i> farms have no turbine layout in the dataset, so their output is the free-stream power curve minus an assumed 10% wake loss.<br><br><b>Disclaimer:</b> all figures are model estimates, not measured output, and not advice of any kind. Personal non-commercial project, not affiliated with any wind farm, operator or data provider.<br><br>Turbine data: <a href='https://doi.org/10.5281/zenodo.17311571' style='color:inherit'>EuroWindWakes European Offshore Dataset</a> contributors, © OpenStreetMap contributors, EMODnet (ODbL). Farm outlines: own compilation, partly from EMODnet Human Activities. Coastlines: Natural Earth. Farms outside Europe: <a href='https://doi.org/10.6084/m9.figshare.13280252' style='color:inherit'>Global offshore wind turbine dataset</a> (Zhang, Tian, Sengupta, Zhang &amp; Si 2021, Sentinel-1 detections to 2021, CC0), with the project names and capacities given there; turbine types estimated. Newer farms outside Europe and the Estonian onshore demo: © OpenStreetMap contributors (ODbL). Generation, load, flows and day-ahead prices: <a href='https://transparency.entsoe.eu' style='color:inherit'>ENTSO-E Transparency Platform</a>. Gas storage and LNG: <a href='https://agsi.gie.eu' style='color:inherit'>GIE AGSI+</a> / <a href='https://alsi.gie.eu' style='color:inherit'>ALSI</a>. Gas flows: <a href='https://transparency.entsog.eu' style='color:inherit'>ENTSOG Transparency Platform</a> (daily physical flows; point positions approximate, georeferenced from the ENTSOG map). High-voltage grid: <a href='https://zenodo.org/records/14144752' style='color:inherit'>PyPSA-Eur prebuilt network</a> (Xiong, Fioriti, Neumann, Riepin &amp; Brown), from © OpenStreetMap contributors (ODbL). Bathymetry: <a href='https://emodnet.ec.europa.eu/en/bathymetry' style='color:inherit'>EMODnet Bathymetry Consortium</a>, Digital Terrain Model (CC BY 4.0). Wake models: PyWake (DTU).";
addEventListener("resize",draw);size();Object.assign(V,fit(HOME,0));clampV();$("M").value="t";$("K").value=K_DEF.t;$("kl").textContent="Wake expansion A";moSet(MO);draw();
