"""Write web/config.js: the page's build-time settings (spec 3 step 2, push 5; replaces the `sed` on index.html).

    CARTO_KEY=... python scripts/build_config.py [--out web/config.js]

The file is generated at deploy time and never committed (.gitignore). The page loads it as a plain script before
anything else and reads `window.CFG`; when the file is missing (local test, fork without secrets) every value falls
back: the CARTO basemaps use the old keyless host (tiles carry a watermark), and nothing else changes.

Keys:
    cartoKey   CARTO basemaps API key (Actions secret CARTO_KEY); client-side by nature, visible in the served page
    builtAt    UTC time this file was written
    schema     data-file schema versions, the same table as scripts/build_meta.py / docs/DATA_CONTRACT.md
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_meta import SCHEMAS  # noqa: E402


def config() -> dict:
    return {
        "cartoKey": os.environ.get("CARTO_KEY", "") or "",
        "builtAt": datetime.now(timezone.utc).isoformat(timespec="minutes"),
        "schema": SCHEMAS,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "web" / "config.js"))
    a = ap.parse_args()
    cfg = config()
    Path(a.out).write_text("// generated by scripts/build_config.py at deploy time; not committed\nwindow.CFG="
                           + json.dumps(cfg, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"config.js: cartoKey {'set' if cfg['cartoKey'] else 'NOT set (keyless CARTO tiles, watermark)'}, built {cfg['builtAt']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
